name: fsspec-reference-maker
channels:
  - conda-forge
  - default
dependencies:
  - python=3.8
  - fsspec-reference-maker
  - fsspec
  - s3fs
  - xarray
  - matplotlib
  - hvplot
  - ujson
  - dask
  - h5py
  - jupyterlab
  - nodejs
  - metpy
  - pip:
    - dask_labextension